### ISSUE TITLE
Trouble with initializing Narrative Model

### ISSUE THREAD

**Issue by jmrifo** [relatio-nlp/relatio#94]
I am running relatio(0.3.0) in python 3.7.16 and I have followed the tutorials, and I have gotten until calling on the NarrativeModel function, but now am running into issues I havent been able to fix. 

I dont have a strong preference for what Embedding Model to use, but I have tried multiple (Spacy, Sentece-Transformers, GloVe) and none of them work for me.

Thanks!
Johannes
---------
I want to run:

```
from relatio.narrative_models import NarrativeModel

from relatio import Embeddings


nlp_model = Embeddings("spaCy", 'en_core_web_lg') 

m = NarrativeModel(clustering = None,
                    PCA = True,
                    UMAP = True,
                    known_entities = top_known_entities,
                    assignment_to_known_entities = 'character_matching',
                    embeddings_model = nlp_model 
                    )
```
     
-------------               
and my error is:

```

✘ No compatible package found for 'all-MiniLM-L6-v2' (spaCy v3.3.3)

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1


%tb
Traceback (most recent call last):

  File "/Users/johannesrenz/Documents/relatio_2CTA.py", line 130, in <module>
    #%% figures

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/relatio/narrative_models.py", line 112, in __init__
    embeddings_type=embeddings_type, embeddings_model=embeddings_model

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/relatio/embeddings.py", line 84, in __init__
    self._embeddings_model = EmbeddingsClass(embeddings_model, **kwargs)

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/relatio/embeddings.py", line 199, in __init__
    spacy_download(model)

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/spacy/cli/download.py", line 68, in download
    version = get_version(model_name, compatibility)

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/spacy/cli/download.py", line 99, in get_version
    exits=1,

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/wasabi/printer.py", line 85, in fail
    title, text, style=MESSAGES.FAIL, show=show, spaced=spaced, exits=exits

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/wasabi/printer.py", line 249, in _get_msg
    title, text, color=style, icon=style, show=show, spaced=spaced, exits=exits

  File "/Users/johannesrenz/opt/anaconda3/envs/relatio2/lib/python3.7/site-packages/wasabi/printer.py", line 155, in text
    sys.exit(exits)

SystemExit: 1

```

**Comment by jmrifo** [comment]
Issue solved, i believe the problem was that i had previously downloaded the spacy model with spacy directly and the model version was incompatible with the narrative model.
